### ISSUE TITLE
Error compiling with GHC 9.0

### ISSUE THREAD

**Issue by kozross** [mstksg/nonempty-containers#10]
When I try and build with GHC 9.0, I get an error like this:

```
[ 1 of 12] Compiling Data.IntMap.NonEmpty.Internal ( src/Data/IntMap/NonEmpty/Internal.hs, dist/build/Data/IntMap/NonEmpty/Internal.o, dist/build/Data/IntMap/NonEmpty/Internal.dyn_o )

src/Data/IntMap/NonEmpty/Internal.hs:184:20: error:
    • Couldn't match type: c (t0 a)
                     with: forall d. Data d => c (t d)
      Expected: (forall d. Data d => c (t d)) -> Maybe (c (NEIntMap a))
        Actual: c (t0 a) -> Maybe (c (NEIntMap a))
    • In the expression: gcast1
      In an equation for ‘dataCast1’: dataCast1 = gcast1
      In the instance declaration for ‘Data (NEIntMap a)’
    • Relevant bindings include
        dataCast1 :: (forall d. Data d => c (t d))
                     -> Maybe (c (NEIntMap a))
          (bound at src/Data/IntMap/NonEmpty/Internal.hs:184:3)
    |
184 |   dataCast1      = gcast1
    |                    ^^^^^^
```

**Comment by andremarianiello** [comment]
FYI @kozross I believe I fixed this in my PR https://github.com/mstksg/nonempty-containers/pull/11
