### ISSUE TITLE
Support for `containers-0.8`.

### ISSUE THREAD

**Issue by jonathanknowles** [mstksg/nonempty-containers#17]
Version [`0.8`](https://hackage.haskell.org/package/containers-0.8) of the `containers` package has been released. 🎉

The `nonempty-containers` package currently has no upper bound on `containers`:

https://github.com/mstksg/nonempty-containers/blob/de9ba5c7bee00003f9961b4134a571f022d62b45/nonempty-containers.cabal#L53-L57

However, when trying to build with `containers-0.8`, compilation fails with:
```hs
$ cabal build all --constraint=containers==0.8 --allow-newer=containers
Building library for nonempty-containers-0.3.4.5...
[ 1 of 12] Compiling Data.IntMap.NonEmpty.Internal ( src/Data/IntMap/NonEmpty/Internal.hs, /home/jsk/projects/jonathanknowles/nonempty-containers/dist-newstyle/build/x86_64-linux/ghc-9.10.1/nonempty-containers-0.3.4.5/build/Data/IntMap/NonEmpty/Internal.o, /home/jsk/projects/jonathanknowles/nonempty-containers/dist-newstyle/build/x86_64-linux/ghc-9.10.1/nonempty-containers-0.3.4.5/build/Data/IntMap/NonEmpty/Internal.dyn_o ) [Source file changed]
src/Data/IntMap/NonEmpty/Internal.hs:723:9: error: [GHC-27346]
    • The data constructor ‘Bin’ should have 3 arguments, but has been given 4
    • In the pattern: Bin p m l r
      In an equation for ‘go’:
          go (Bin p m l r) = liftA2 (flip (Bin p m)) (go r) (go l)
      In an equation for ‘traverseMapWithKey’:
          traverseMapWithKey f
            = go
            where
                go Nil = pure Nil
                go (Tip k v) = Tip k <$> f k v
                go (Bin p m l r) = liftA2 (flip (Bin p m)) (go r) (go l)
    |
723 |     go (Bin p m l r) = liftA2 (flip (Bin p m)) (go r) (go l)
```

**Comment by jonathanknowles** [comment]
It seems the cause of the compilation failure is that `containers-0.8` changed the constructors of `IntMap`, removing the "mask" field.

Luckily, these constructors only seem to be used in the `Data.IntMap.NonEmpty.Internal.traverseMapWithKey` function.

I had a go at fixing it with [this commit](https://github.com/mstksg/nonempty-containers/commit/34b507b31deba4f11330b44f9acf454bcb02aaa4), which at least makes it possible to compile the library again.

However, the test suite now fails with a (seemingly unrelated) error:
```hs
  Tests.Set                                                                                
    fromAscList:        FAIL (0.10s)                                                       
        ✗ <interactive> failed at test/Tests/Util.hs:394:14                                
          after 75 tests and 7 shrinks.
          shrink path: 75:bG2hIe2                                                          
                                                                                           
              ┏━━ test/Tests/Util.hs ━━━
          384 ┃ runTT :: Monad m => TestType a b -> a -> b -> PropertyT m ()
          385 ┃ runTT = \case      
          386 ┃   TTNEMap -> \x y -> do                                                    
          387 ┃     assert $ NEM.valid y                                                   
          388 ┃     unKMap x === unKMap (NEM.IsNonEmpty y)                                 
          389 ┃   TTNEIntMap -> \x y -> do                                                 
          390 ┃     assert $ NEIM.valid y                                                  
          391 ┃     x === NEIM.IsNonEmpty y                                                
          392 ┃   TTNESet -> \x y -> do                                                                                                                                               
          393 ┃     assert $ NES.valid y
          394 ┃     unKSet x === unKSet (NES.IsNonEmpty y)                                                                                                                            
              ┃     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              ┃     │ ━━━ Failed (- lhs) (+ rhs) ━━━                                       
              ┃     │ - fromList [ ( -95 , "a" ) ]      
              ┃     │ + fromList [ ( -95 , "" ) ]
```

**Comment by jonathanknowles** [comment]
I was able to get the test suite passing again with [this commit](3de17bea7a28ff23cfb8895d92145489a46d6247), which makes the bias of `combineEq` dependent on the version of `containers`.

**Comment by jonathanknowles** [comment]
I've combined the above commits into a single PR here:
- https://github.com/mstksg/nonempty-containers/pull/18

**Comment by jonathanknowles** [comment]
I discovered a change in the behaviour of `Set.from{Asc,Desc}List` w.r.t. duplicate elements from `containers-0.7` to `containers-0.8`.

We can use the `K` type from `Tests.Util` to demonstrate this.

With `containers-0.7`, `Set.from{Asc,Desc}List` chooses the **_first_** occurrence of any duplicated element:
```hs
$ cabal repl nonempty-containers-test --constraint=containers==0.7
> import qualified Data.Set as Set
> import Tests.Util
> Set.fromAscList [K 'a' 1, K 'a' 2]
fromList [K {getKX = 'a', getKY = 1}]
> Set.fromDescList [K 'a' 1, K 'a' 2]
fromList [K {getKX = 'a', getKY = 1}]
```

With `containers-0.8`, `Set.from{Asc,Desc}List` chooses the **_last_** occurrence of any duplicated element:
```hs
$ cabal repl nonempty-containers-test --constraint=containers==0.8 --allow-newer=containers
> import qualified Data.Set as Set
> import Tests.Util
> Set.fromAscList [K 'a' 1, K 'a' 2]
fromList [K {getKX = 'a', getKY = 2}]
> Set.fromDescList [K 'a' 1, K 'a' 2]
fromList [K {getKX = 'a', getKY = 2}]
```

In contrast, the behaviour of `Set.fromList` remains unchanged across versions, and chooses the **_last_** occurrence of any duplicate element:
```hs
> Set.fromList [K 'a' 1, K 'a' 2]
fromList [K {getKX = 'a', getKY = 2}]
> Set.fromList [K 'a' 1, K 'a' 2]
fromList [K {getKX = 'a', getKY = 2}]
```

**Comment by jonathanknowles** [comment]
I've just discovered this change in the behaviour of `Set.from{Asc,Desc}List` was mentioned here:
https://github.com/haskell/containers/issues/1032
Presumably, the change was introduced in this PR:

It seems the relevant change was made in this PR, which was included in `containers-0.8`:
https://github.com/haskell/containers/pull/1083

**Comment by jonathanknowles** [comment]
Related issue in `containers`: https://github.com/haskell/containers/issues/1118

**Comment by danwdart** [comment]
What's happening here? This seems to be enough.

**Comment by jonathanknowles** [comment]
> What's happening here? This seems to be enough.

@danwdart There's an open PR to fix this issue here:
- https://github.com/mstksg/nonempty-containers/pull/18

I'll try again to ping the author @mstksg.

**Comment by mstksg** [comment]
Fixed with #18
